#!/bin/sh

#-----------#
# Anukranan #
# kshrc     #
#-----------#

#----------------------------------------#
# System
#----------------------------------------#

[[ $- != *i* ]] && return
PS1="\[\e[1;32m\][\u \W]\[\e[0m\]> " # It just works.


#----------------------------------------#
# Aesthetics
#----------------------------------------#

(cat ~/.cache/wal/sequences &)
. ~/.cache/wal/colors-tty.sh


#----------------------------------------#
# Aliases
#----------------------------------------#

# Normal
alias eg='emacs -nw'
alias jg='jmacs'
alias cdp='cd $HOME/Documents/Programming'
alias ls='ls --color=auto -A -T 2 -1 -X -r -h --group-directories-first'

# Package manager
alias xq='xbps-query'
alias xqe='xbps-query -Rs'
alias xqi='xbps-query -l'

alias xin='doas xbps-install -Su'
alias xre='doas xbps-remove -Ro'


#----------------------------------------#
# Environment variables
#----------------------------------------#

#export POSIXLY_CORRECT=yes

# Env
export ENV='$HOME/.config/ksh/kshrc'
export EDITOR='jmacs'

# Wayland
export MOZ_ENABLE_WAYLAND=1

export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export ELM_ENGINE=wayland_egl
export ELM_DISPLAY=wl
export ECORE_EVAS_ENGINE=wayland_egl

# These can break Steam games. Set SDL_VIDEODRIVER=x11 in the Steam advanced options.
# Possibly also disable the second variable entirely.
#export SDL_VIDEODRIVER=wayland
#export SDL_DYNAMIC_API=/usr/lib/libSDL2-2.0.so.0

#export BEMENU_BACKEND=wayland

export _JAVA_AWT_WM_NONREPARENTING=1
